[package]
name = "entertainment-tracker"
version = "0.1.0"
authors = ["farooq-azam-khan <farooq1.khan@ryerson.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
dotenv = "0.15.0"

